version: 2
updates:
  - package-ecosystem: "bun" # See documentation for possible values
    directories:
      - "/**/*" # Location of package manifests
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
