# Paths filter configuration for alc-lovers project
# This file defines which files trigger which workflows

# Backend filters - TypeScript and configuration files
backend:
  - "apps/backend/**"
  - "!apps/backend/**/*.md"
  - "!apps/backend/**/*.txt"
  - "!apps/backend/**/*.log"

# Frontend filters - TypeScript, JSX, and configuration files
frontend:
  - "apps/frontend/**"
  - "!apps/frontend/**/*.md"
  - "!apps/frontend/**/*.txt"
  - "!apps/frontend/**/*.log"

# Documentation changes
docs:
  - "docs/**"
  - "README.md"
  - "*.md"

# Configuration changes
config:
  - "biome.json"
  - "tsconfig.json"
  - "wrangler.jsonc"
  - "package.json"
  - "bun.lock"
  - ".github/**"

# TypeScript files specifically
typescript:
  - "*.ts"
  - "*.tsx"
  - "!**/*.d.ts"

# JavaScript files specifically
javascript:
  - "*.js"
  - "*.jsx"
  - "*.mjs"
